# This tells Docker that our new image is based on the alpine image
FROM alpine

# Let's create the hello.txt file again
RUN echo Hello Alpine! > hello.txt

# Let's install curl!
RUN apk add curl
